export type Creator = {
  name: string;
  handle: string;
  link: string;
  followers?: string;
};

export const CREATORS: Creator[] = [
  { name: "Abhinandan Sarkar", handle: "abhinandan__sarkar", link: "https://www.instagram.com/abhinandan__sarkar" },
  { name: "Abhishek Ghosh", handle: "thefoodgambler", link: "https://www.instagram.com/thefoodgambler" },
  { name: "Adrija", handle: "awwdrijaa", link: "https://www.instagram.com/awwdrijaa" },
  { name: "Adrija Ghoshal", handle: "adrija.gal", link: "https://www.instagram.com/adrija.gal" },
  { name: "Afrin Mustafi", handle: "afrin.mustafi", link: "https://www.instagram.com/afrin.mustafi" },
  { name: "Ahana Roy", handle: "ahana8243", link: "https://www.instagram.com/ahana8243" },
  { name: "Aishwarya Sen", handle: "aishwarya.sen.9", link: "https://www.instagram.com/aishwarya.sen.9" },
  { name: "Amrita", handle: "amritadebnath___", link: "https://www.instagram.com/amritadebnath___" },
  { name: "Ananyyaa Biswas", handle: "iamanannyaabiswaas", link: "https://www.instagram.com/iamanannyaabiswaas" },
  { name: "Angela Saha", handle: "engela.saha", link: "https://www.instagram.com/engela.saha" },
  { name: "Anindita Das", handle: "silent__daydreamer", link: "https://www.instagram.com/silent__daydreamer" },
  { name: "Ankita Mallick", handle: "_ankita_mallick_", link: "https://www.instagram.com/_ankita_mallick_" },
  { name: "Anulipee Ghosh", handle: "anulipee_ghosh", link: "https://www.instagram.com/anulipee_ghosh" },
  { name: "Anupurba Bose", handle: "hey.anuupurba", link: "https://www.instagram.com/hey.anuupurba" },
  { name: "Anusmita Dutta", handle: "miss_dutta1", link: "https://www.instagram.com/miss_dutta1" },
  { name: "Baishakhi Dutta", handle: "gorgeous_junk_55", link: "https://www.instagram.com/gorgeous_junk_55" },
  { name: "Bani Biswas", handle: "baaani___", link: "https://www.instagram.com/baaani___" },
  { name: "Bhubaneswar Food Blogger", handle: "_.moodyfoody._", link: "https://www.instagram.com/_.moodyfoody._" },
  { name: "Bihu Ghosh", handle: "bangaliflavours", link: "https://www.instagram.com/bangaliflavours" },
  { name: "Borini Chakraborty", handle: "borninichakraborty_official", link: "https://www.instagram.com/borninichakraborty_official" },
  { name: "Chef Neha Dipak Shah", handle: "nehadeepakshah", link: "https://www.instagram.com/nehadeepakshah" },
  { name: "Debadri Bishnu", handle: "foodie_banker1", link: "https://www.instagram.com/foodie_banker1" },
  { name: "Debaparna", handle: "debaparna_paul_chowdhury", link: "https://www.instagram.com/debaparna_paul_chowdhury" },
  { name: "Debjani Banerjee", handle: "_debjani_banerjee", link: "https://www.instagram.com/_debjani_banerjee" },
  { name: "Dipanwita Nath", handle: "dipanwitaa_nath", link: "https://www.instagram.com/dipanwitaa_nath" },
  { name: "Dipanwita Rakshit", handle: "dipanwitarakshit", link: "https://www.instagram.com/dipanwitarakshit" },
  { name: "Dr. Pramita Sen", handle: "mrignaini_007", link: "https://www.instagram.com/mrignaini_007" },
  { name: "Ena Saha", handle: "ena1996gemini", link: "https://www.instagram.com/ena1996gemini" },
  { name: "Gargi", handle: "gargi_gangopadhyay", link: "https://www.instagram.com/gargi_gangopadhyay" },
  { name: "Garima Banka", handle: "garima_banka", link: "https://www.instagram.com/garima_banka" },
  { name: "Heena Aftab", handle: "unseen_miracles", link: "https://www.instagram.com/unseen_miracles" },
  { name: "Indrakshi Dey", handle: "indraksshidey_official", link: "https://www.instagram.com/indraksshidey_official" },
  { name: "Joyeeta Banerjee", handle: "joyeetabanerjee11", link: "https://www.instagram.com/joyeetabanerjee11" },
  { name: "Kamelia Roy", handle: "thealwayshungrylady", link: "https://www.instagram.com/thealwayshungrylady" },
  { name: "Kheyali Mondaal", handle: "kheyali_mofficial", link: "https://www.instagram.com/kheyali_mofficial" },
  { name: "Lokasree Dutta", handle: "ratri__003", link: "https://www.instagram.com/ratri__003" },
  { name: "Manpreet Singh", handle: "manpreetverse", link: "https://www.instagram.com/manpreetverse" },
  { name: "Megha Dasgupta", handle: "megha.dasgupta", link: "https://www.instagram.com/megha.dasgupta" },
  { name: "Miss Mahotra", handle: "shuchi_malhotra", link: "https://www.instagram.com/shuchi_malhotra" },
  { name: "Mousumi Guha", handle: "abong_mousumi", link: "https://www.instagram.com/abong_mousumi" },
  { name: "Neeru", handle: "neeru_starlet", link: "https://www.instagram.com/neeru_starlet" },
  { name: "Nidhi", handle: "nids_style_secret", link: "https://www.instagram.com/nids_style_secret" },
  { name: "Nimah Lamha", handle: "nimah_lamah", link: "https://www.instagram.com/nimah_lamah" },
  { name: "Oishi Roy Chowdhury", handle: "_kolkatacravings_", link: "https://www.instagram.com/_kolkatacravings_" },
  { name: "Olivia Malakar", handle: "oliviamalakar", link: "https://www.instagram.com/oliviamalakar" },
  { name: "Olivia Mandal", handle: "oliviaaaa.m_", link: "https://www.instagram.com/oliviaaaa.m_" },
  { name: "Pallabi Guha", handle: "pallabiguha", link: "https://www.instagram.com/pallabiguha" },
  { name: "Pooja And Arijit", handle: "lady_from_90s", link: "https://www.instagram.com/lady_from_90s" },
  { name: "Pragya Mukherjee", handle: "p_r_a_g_y_a_08", link: "https://www.instagram.com/p_r_a_g_y_a_08" },
  { name: "Pramita Ghosh", handle: "cuteparamita", link: "https://www.instagram.com/cuteparamita" },
  { name: "Prapti Chowdhury", handle: "prapti_chowdhuryy", link: "https://www.instagram.com/prapti_chowdhuryy" },
  { name: "Prarona Bhattacharjee", handle: "iamprarona", link: "https://www.instagram.com/iamprarona" },
  { name: "Preeti Sarkar", handle: "prettysheis.official", link: "https://www.instagram.com/prettysheis.official" },
  { name: "Priyanka Biswas", handle: "pri_yankabiswas22", link: "https://www.instagram.com/pri_yankabiswas22" },
  { name: "Priyanka Bysac", handle: "priyanka_bysack", link: "https://www.instagram.com/priyanka_bysack" },
  { name: "Priyanka Tiwari", handle: "_priyankatiwari", link: "https://www.instagram.com/_priyankatiwari" },
  { name: "Priyasree Mukherjee", handle: "priyarsee_mukherjee", link: "https://www.instagram.com/priyarsee_mukherjee" },
  { name: "Punam Mohanty", handle: "____.punam._____", link: "https://www.instagram.com/____.punam._____" },
  { name: "Rakshita", handle: "rakshitasatpute", link: "https://www.instagram.com/rakshitasatpute" },
  { name: "Reema", handle: "reema98___", link: "https://www.instagram.com/reema98___" },
  { name: "Renu And Suraj", handle: "0foodgasm0", link: "https://www.instagram.com/0foodgasm0" },
  { name: "Richa Sharma", handle: "richaa_13", link: "https://www.instagram.com/richaa_13" },
  { name: "Rikhia Roy Chowdhury", handle: "rikhia_rc", link: "https://www.instagram.com/rikhia_rc" },
  { name: "Rimpa Roy", handle: "_rimparoy1official_", link: "https://www.instagram.com/_rimparoy1official_" },
  { name: "Riya Mallick", handle: "mallick_riya9", link: "https://www.instagram.com/mallick_riya9" },
  { name: "Roja", handle: "_vibeswith.roja_", link: "https://www.instagram.com/_vibeswith.roja_" },
  { name: "Rooqma Ray", handle: "rayrooqma", link: "https://www.instagram.com/rayrooqma" },
  { name: "Roshni Chakraborty", handle: "roshni_chakraborty_", link: "https://www.instagram.com/roshni_chakraborty_" },
  { name: "Roshni Sharma", handle: "roshni_24_official", link: "https://www.instagram.com/roshni_24_official" },
  { name: "Rutuja Bhagwat", handle: "theprettycitygirl", link: "https://www.instagram.com/theprettycitygirl" },
  { name: "Samragngi Roy", handle: "samragngi_roy", link: "https://www.instagram.com/samragngi_roy" },
  { name: "Sanandita Saha", handle: "____sana_saha00____", link: "https://www.instagram.com/____sana_saha00____" },
  { name: "Sandipta Sen", handle: "sandiptasen", link: "https://www.instagram.com/sandiptasen" },
  { name: "Satyajit", handle: "satyajit_siliguri", link: "https://www.instagram.com/satyajit_siliguri" },
  { name: "Sayani Pradhan", handle: "sayani_pradhan", link: "https://www.instagram.com/sayani_pradhan" },
  { name: "Sayena", handle: "scrumptious.siliguri", link: "https://www.instagram.com/scrumptious.siliguri" },
  { name: "Sherya Singh", handle: "shreyhaha_", link: "https://www.instagram.com/shreyhaha_" },
  { name: "Soham Sinha", handle: "kolkatadelites", link: "https://www.instagram.com/kolkatadelites" },
  { name: "Sohini Guha Roy", handle: "sohiniguharoy_official", link: "https://www.instagram.com/sohiniguharoy_official" },
  { name: "Sohini Sourajit", handle: "_sohini_sourajit", link: "https://www.instagram.com/_sohini_sourajit" },
  { name: "Sonika Chauhan", handle: "storiesofsonika", link: "https://www.instagram.com/storiesofsonika" },
  { name: "Sreejita", handle: "missgastronomic", link: "https://www.instagram.com/missgastronomic" },
  { name: "Srijoni Chatterjee", handle: "srijonichatterje", link: "https://www.instagram.com/srijonichatterje" },
  { name: "Srishti Mukherjee", handle: "shrishtea_", link: "https://www.instagram.com/shrishtea_" },
  { name: "Sristi Pradhan", handle: "shrewiish", link: "https://www.instagram.com/shrewiish" },
  { name: "Subarna Majumder", handle: "mountaingirl_subarna", link: "https://www.instagram.com/mountaingirl_subarna" },
  { name: "Subhashree Khandal", handle: "subhashreekhandai", link: "https://www.instagram.com/subhashreekhandai" },
  { name: "Subhasmita Bal", handle: "onlythessb", link: "https://www.instagram.com/onlythessb" },
  { name: "Sukanya Dutta", handle: "wowsukannya", link: "https://www.instagram.com/wowsukannya" },
  { name: "Sulagna Dey", handle: "sulagnaaa.dey", link: "https://www.instagram.com/sulagnaaa.dey" },
  { name: "Sunitee Siddiqui", handle: "_hotmess_mama", link: "https://www.instagram.com/_hotmess_mama" },
  { name: "Susmita Das", handle: "dsusmita", link: "https://www.instagram.com/dsusmita" },
  { name: "Susmitha Deb", handle: "officialsusmitadeb__", link: "https://www.instagram.com/officialsusmitadeb__" },
  { name: "Suvo Jit", handle: "suvlogging", link: "https://www.instagram.com/suvlogging" },
  { name: "Sweta Patra", handle: "_vibing.high_", link: "https://www.instagram.com/_vibing.high_" },
  { name: "Tanurima Hazra", handle: "tanurimahazra", link: "https://www.instagram.com/tanurimahazra" },
  { name: "Tithi Basu", handle: "c_h_i_r_p_s", link: "https://www.instagram.com/c_h_i_r_p_s" },
  { name: "Titiksha Das", handle: "ira_chauhan12", link: "https://www.instagram.com/ira_chauhan12" },
  { name: "Tripti Guha", handle: "triptiggupta", link: "https://www.instagram.com/triptiggupta" },
  { name: "Trisha Ganguly", handle: "trisha_gunja_ganguly", link: "https://www.instagram.com/trisha_gunja_ganguly" },
];
