export type Creator = {
  name: string;
  handle: string;
  link: string;
  img?: string;
  imgType?: "photo" | "avatar";
  followers?: string;
  location?: string;
};

export function slugify(name: string) {
  return name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

export const CREATORS: Creator[] = [
  { name: "Abhinandan Sarkar", handle: "abhinandan__sarkar", link: "https://www.instagram.com/abhinandan__sarkar", img: "/Influencers/1.png", imgType: "avatar", followers: "169k" },
  { name: "Abhishek Ghosh", handle: "thefoodgambler", link: "https://www.instagram.com/thefoodgambler", img: "/Influencers/2.png", imgType: "avatar", followers: "183k" },
  { name: "Adrija", handle: "awwdrijaa", link: "https://www.instagram.com/awwdrijaa", img: "/Influencers/3.png", imgType: "avatar", followers: "90.6k" },
  { name: "Adrija Ghoshal", handle: "adrija.gal", link: "https://www.instagram.com/adrija.gal", img: "/Influencers/4.png", imgType: "avatar", followers: "87.5k" },
  { name: "Afrin Mustafi", handle: "afrin.mustafi", link: "https://www.instagram.com/afrin.mustafi", img: "/Influencers/5.png", imgType: "avatar", followers: "78.8k" },
  { name: "Ahana Roy", handle: "ahana8243", link: "https://www.instagram.com/ahana8243", img: "/Influencers/6.png", imgType: "avatar", followers: "58.1k" },
  { name: "Aishwarya Sen", handle: "aishwarya.sen.9", link: "https://www.instagram.com/aishwarya.sen.9", img: "/Influencers/7.png", imgType: "avatar", followers: "26.2k" },
  { name: "Amrita", handle: "amritadebnath___", link: "https://www.instagram.com/amritadebnath___", img: "/Influencers/8.png", imgType: "avatar", followers: "128k" },
  { name: "Ananyyaa Biswas", handle: "iamanannyaabiswaas", link: "https://www.instagram.com/iamanannyaabiswaas", img: "/Influencers/9.png", imgType: "avatar", followers: "237k" },
  { name: "Angela Saha", handle: "engela.saha", link: "https://www.instagram.com/engela.saha", img: "/Influencers/10.png", imgType: "avatar", followers: "79.4k" },
  { name: "Ankita Mallick", handle: "_ankita_mallick_", link: "https://www.instagram.com/_ankita_mallick_", img: "/Influencers/11.png", imgType: "photo", followers: "587k" },
  { name: "Anulipee Ghosh", handle: "anulipee_ghosh", link: "https://www.instagram.com/anulipee_ghosh", img: "/Influencers/12.png", imgType: "photo", followers: "114k" },
  { name: "Anupurba Bose", handle: "hey.anuupurba", link: "https://www.instagram.com/hey.anuupurba", img: "/Influencers/13.png", imgType: "photo", followers: "15.8k" },
  { name: "Anusmita Dutta", handle: "miss_dutta1", link: "https://www.instagram.com/miss_dutta1", img: "/Influencers/14.png", imgType: "photo", followers: "440k" },
  { name: "Baishakhi Dutta", handle: "gorgeous_junk_55", link: "https://www.instagram.com/gorgeous_junk_55", img: "/Influencers/15.png", imgType: "avatar", followers: "23.2k" },
  { name: "Bani Biswas", handle: "baaani___", link: "https://www.instagram.com/baaani___", img: "/Influencers/16.png", imgType: "photo", followers: "75.9k" },
  { name: "Bhubaneswar Food Blogger", handle: "_.moodyfoody._", link: "https://www.instagram.com/_.moodyfoody._", img: "/Influencers/17.png", imgType: "avatar", followers: "37.1k" },
  { name: "Bihu Ghosh", handle: "bangaliflavours", link: "https://www.instagram.com/bangaliflavours", img: "/Influencers/18.png", imgType: "avatar", followers: "90.2k" },
  { name: "Borini Chakraborty", handle: "borninichakraborty_official", link: "https://www.instagram.com/borninichakraborty_official", img: "/Influencers/19.png", imgType: "photo", followers: "108k" },
  { name: "Chef Neha Dipak Shah", handle: "nehadeepakshah", link: "https://www.instagram.com/nehadeepakshah", img: "/Influencers/20.png", imgType: "avatar", followers: "2.3m" },
  { name: "Debadri Bishnu", handle: "foodie_banker1", link: "https://www.instagram.com/foodie_banker1", img: "/Influencers/21.png", imgType: "avatar", followers: "22k" },
  { name: "Debaparna", handle: "debaparna_paul_chowdhury", link: "https://www.instagram.com/debaparna_paul_chowdhury", img: "/Influencers/22.png", imgType: "photo", followers: "344k" },
  { name: "Debjani Banerjee", handle: "_debjani_banerjee", link: "https://www.instagram.com/_debjani_banerjee", img: "/Influencers/23.png", imgType: "photo", followers: "24.1k" },
  { name: "Dipanwita Nath", handle: "dipanwitaa_nath", link: "https://www.instagram.com/dipanwitaa_nath", img: "/Influencers/24.png", imgType: "photo", followers: "21.6k" },
  { name: "Dipanwita Rakshit", handle: "dipanwitarakshit", link: "https://www.instagram.com/dipanwitarakshit", img: "/Influencers/25.png", imgType: "photo", followers: "251k" },
  { name: "Dr. Pramita Sen", handle: "mrignaini_007", link: "https://www.instagram.com/mrignaini_007", img: "/Influencers/26.png", imgType: "photo", followers: "124k" },
  { name: "Ena Saha", handle: "ena1996gemini", link: "https://www.instagram.com/ena1996gemini", img: "/Influencers/27.png", imgType: "photo", followers: "1.4m" },
  { name: "Gargi", handle: "gargi_gangopadhyay", link: "https://www.instagram.com/gargi_gangopadhyay", img: "/Influencers/28.png", imgType: "photo", followers: "73.2k" },
  { name: "Garima Banka", handle: "garima_banka", link: "https://www.instagram.com/garima_banka", img: "/Influencers/29.png", imgType: "photo", followers: "40.9k" },
  { name: "Heena Aftab", handle: "unseen_miracles", link: "https://www.instagram.com/unseen_miracles", img: "/Influencers/30.png", imgType: "photo", followers: "49.5k" },
  { name: "Indrakshi Dey", handle: "indraksshidey_official", link: "https://www.instagram.com/indraksshidey_official", img: "/Influencers/31.png", imgType: "photo", followers: "49.4k" },
  { name: "Joyeeta Banerjee", handle: "joyeetabanerjee11", link: "https://www.instagram.com/joyeetabanerjee11", img: "/Influencers/32.png", imgType: "photo", followers: "234k" },
  { name: "Kamelia Roy", handle: "thealwayshungrylady", link: "https://www.instagram.com/thealwayshungrylady", img: "/Influencers/33.png", imgType: "photo", followers: "104k" },
  { name: "Kheyali Mondaal", handle: "kheyali_mofficial", link: "https://www.instagram.com/kheyali_mofficial", img: "/Influencers/34.png", imgType: "photo", followers: "124k" },
  { name: "Lokasree Dutta", handle: "ratri__003", link: "https://www.instagram.com/ratri__003", img: "/Influencers/35.png", imgType: "photo", followers: "145k" },
  { name: "Manpreet Singh", handle: "manpreetverse", link: "https://www.instagram.com/manpreetverse", img: "/Influencers/36.png", imgType: "photo", followers: "15k" },
  { name: "Megha Dasgupta", handle: "megha.dasgupta", link: "https://www.instagram.com/megha.dasgupta", img: "/Influencers/37.png", imgType: "photo", followers: "180k" },
  { name: "Miss Mahotra", handle: "shuchi_malhotra", link: "https://www.instagram.com/shuchi_malhotra", img: "/Influencers/38.png", imgType: "photo", followers: "49.3k", location: "Kolkata" },
  { name: "Mousumi Guha", handle: "abong_mousumi", link: "https://www.instagram.com/abong_mousumi", img: "/Influencers/39.png", imgType: "photo", followers: "40.2k" },
  { name: "Neeru", handle: "neeru_starlet", link: "https://www.instagram.com/neeru_starlet", img: "/Influencers/40.png", imgType: "photo", followers: "140k" },
  { name: "Nidhi", handle: "nids_style_secret", link: "https://www.instagram.com/nids_style_secret", img: "/Influencers/41.png", imgType: "photo", followers: "210k", location: "Kolkata" },
  { name: "Nimah Lamha", handle: "nimah_lamah", link: "https://www.instagram.com/nimah_lamah", img: "/Influencers/42.png", imgType: "photo", followers: "94.3k", location: "Kolkata" },
  { name: "Oishi Roy Chowdhury", handle: "_kolkatacravings_", link: "https://www.instagram.com/_kolkatacravings_", img: "/Influencers/43.png", imgType: "photo", followers: "32.2k" },
  { name: "Olivia Malakar", handle: "oliviamalakar", link: "https://www.instagram.com/oliviamalakar", img: "/Influencers/44.png", imgType: "photo", followers: "243k" },
  { name: "Olivia Mandal", handle: "oliviaaaa.m_", link: "https://www.instagram.com/oliviaaaa.m_", img: "/Influencers/45.png", imgType: "photo", followers: "62.2k" },
  { name: "Pallabi Guha", handle: "pallabiguha", link: "https://www.instagram.com/pallabiguha", img: "/Influencers/46.png", imgType: "photo", followers: "77.2k" },
  { name: "Pooja And Arijit", handle: "lady_from_90s", link: "https://www.instagram.com/lady_from_90s", img: "/Influencers/47.png", imgType: "avatar", followers: "108k" },
  { name: "Pragya Mukherjee", handle: "p_r_a_g_y_a_08", link: "https://www.instagram.com/p_r_a_g_y_a_08", img: "/Influencers/48.png", imgType: "photo", followers: "73.8k" },
  { name: "Pramita Ghosh", handle: "cuteparamita", link: "https://www.instagram.com/cuteparamita", img: "/Influencers/49.png", imgType: "photo", followers: "82.6k" },
  { name: "Prapti Chowdhury", handle: "prapti_chowdhuryy", link: "https://www.instagram.com/prapti_chowdhuryy", img: "/Influencers/50.png", imgType: "photo", followers: "57.2k" },
  { name: "Prarona Bhattacharjee", handle: "iamprarona", link: "https://www.instagram.com/iamprarona", img: "/Influencers/51.png", imgType: "photo", followers: "134k" },
  { name: "Preeti Sarkar", handle: "prettysheis.official", link: "https://www.instagram.com/prettysheis.official", img: "/Influencers/52.png", imgType: "photo", followers: "876k" },
  { name: "Priyanka Biswas", handle: "pri_yankabiswas22", link: "https://www.instagram.com/pri_yankabiswas22", img: "/Influencers/53.png", imgType: "avatar", followers: "345k" },
  { name: "Priyanka Bysac", handle: "priyanka_bysack", link: "https://www.instagram.com/priyanka_bysack", img: "/Influencers/54.png", imgType: "photo", followers: "92.5k" },
  { name: "Priyanka Tiwari", handle: "_priyankatiwari", link: "https://www.instagram.com/_priyankatiwari", img: "/Influencers/55.png", imgType: "photo", followers: "14.8k" },
  { name: "Priyasree Mukherjee", handle: "priyarsee_mukherjee", link: "https://www.instagram.com/priyarsee_mukherjee", img: "/Influencers/56.png", imgType: "avatar", followers: "5216", location: "Kolkata" },
  { name: "Punam Mohanty", handle: "____.punam._____", link: "https://www.instagram.com/____.punam._____", img: "/Influencers/57.png", imgType: "photo", followers: "29.7k", location: "Kolkata" },
  { name: "Rakshita", handle: "rakshitasatpute", link: "https://www.instagram.com/rakshitasatpute", img: "/Influencers/58.png", imgType: "photo", followers: "39.1k", location: "Kolkata" },
  { name: "Reema", handle: "reema98___", link: "https://www.instagram.com/reema98___", img: "/Influencers/59.png", imgType: "photo", followers: "10.4k", location: "Kolkata" },
  { name: "Renu And Suraj", handle: "0foodgasm0", link: "https://www.instagram.com/0foodgasm0", img: "/Influencers/60.jpg", imgType: "avatar", followers: "36.6k" },
  { name: "Richa Sharma", handle: "richaa_13", link: "https://www.instagram.com/richaa_13", img: "/Influencers/61.jpg", imgType: "photo", followers: "3m" },
  { name: "Rikhia Roy Chowdhury", handle: "rikhia_rc", link: "https://www.instagram.com/rikhia_rc", img: "/Influencers/62.jpg", imgType: "photo", followers: "62.9k" },
  { name: "Rimpa Roy", handle: "_rimparoy1official_", link: "https://www.instagram.com/_rimparoy1official_", img: "/Influencers/63.jpg", imgType: "photo", followers: "1.9m" },
  { name: "Riya Mallick", handle: "mallick_riya9", link: "https://www.instagram.com/mallick_riya9", img: "/Influencers/64.jpg", imgType: "photo", followers: "64.2k" },
  { name: "Roja", handle: "_vibeswith.roja_", link: "https://www.instagram.com/_vibeswith.roja_", img: "/Influencers/65.jpg", imgType: "photo", followers: "4707", location: "Kolkata" },
  { name: "Rooqma Ray", handle: "rayrooqma", link: "https://www.instagram.com/rayrooqma", img: "/Influencers/66.jpg", imgType: "photo", followers: "601k" },
  { name: "Roshni Chakraborty", handle: "roshni_chakraborty_", link: "https://www.instagram.com/roshni_chakraborty_", img: "/Influencers/67.jpg", imgType: "photo", followers: "33.3k" },
  { name: "Roshni Sharma", handle: "roshni_24_official", link: "https://www.instagram.com/roshni_24_official", img: "/Influencers/68.jpg", imgType: "photo", followers: "127k" },
  { name: "Rutuja Bhagwat", handle: "theprettycitygirl", link: "https://www.instagram.com/theprettycitygirl", img: "/Influencers/69.jpg", imgType: "photo", followers: "76.5k", location: "Kolkata" },
  { name: "Samragngi Roy", handle: "samragngi_roy", link: "https://www.instagram.com/samragngi_roy", img: "/Influencers/70.jpg", imgType: "photo", followers: "91k" },
  { name: "Sanandita Saha", handle: "____sana_saha00____", link: "https://www.instagram.com/____sana_saha00____", img: "/Influencers/71.jpg", imgType: "photo", followers: "3071", location: "Kolkata" },
  { name: "Sandipta Sen", handle: "sandiptasen", link: "https://www.instagram.com/sandiptasen", img: "/Influencers/72.jpg", imgType: "photo", followers: "1.3m" },
  { name: "Satyajit", handle: "satyajit_siliguri", link: "https://www.instagram.com/satyajit_siliguri", img: "/Influencers/73.jpg", imgType: "photo", followers: "64k", location: "Kolkata" },
  { name: "Sayani Pradhan", handle: "sayani_pradhan", link: "https://www.instagram.com/sayani_pradhan", img: "/Influencers/74.jpg", imgType: "avatar", followers: "708k" },
  { name: "Sayena", handle: "scrumptious.siliguri", link: "https://www.instagram.com/scrumptious.siliguri", img: "/Influencers/75.jpg", imgType: "avatar", followers: "23k", location: "Kolkata" },
  { name: "Sherya Singh", handle: "shreyhaha_", link: "https://www.instagram.com/shreyhaha_", img: "/Influencers/76.jpg", imgType: "photo", followers: "104k", location: "Kolkata" },
  { name: "Soham Sinha", handle: "kolkatadelites", link: "https://www.instagram.com/kolkatadelites", img: "/Influencers/77.jpg", imgType: "avatar", followers: "607k" },
  { name: "Sohini Guha Roy", handle: "sohiniguharoy_official", link: "https://www.instagram.com/sohiniguharoy_official", img: "/Influencers/78.jpg", imgType: "photo", followers: "550k" },
  { name: "Sohini Sourajit", handle: "_sohini_sourajit", link: "https://www.instagram.com/_sohini_sourajit", img: "/Influencers/79.jpg", imgType: "photo", followers: "30.9k" },
  { name: "Sonika Chauhan", handle: "storiesofsonika", link: "https://www.instagram.com/storiesofsonika", img: "/Influencers/80.jpg", imgType: "photo", followers: "73.2k", location: "Kolkata" },
  { name: "Sreejita", handle: "missgastronomic", link: "https://www.instagram.com/missgastronomic", img: "/Influencers/81.png", imgType: "photo", followers: "92.6k" },
  { name: "Srijoni Chatterjee", handle: "srijonichatterje", link: "https://www.instagram.com/srijonichatterje", img: "/Influencers/82.jpg", imgType: "photo", followers: "152k" },
  { name: "Srishti Mukherjee", handle: "shrishtea_", link: "https://www.instagram.com/shrishtea_", img: "/Influencers/83.jpg", imgType: "photo", followers: "27k" },
  { name: "Sristi Pradhan", handle: "shrewiish", link: "https://www.instagram.com/shrewiish", img: "/Influencers/84.png", imgType: "photo", followers: "127k" },
  { name: "Subarna Majumder", handle: "mountaingirl_subarna", link: "https://www.instagram.com/mountaingirl_subarna", img: "/Influencers/85.png", imgType: "photo", followers: "65.9k", location: "Kolkata" },
  { name: "Subhashree Khandal", handle: "subhashreekhandai", link: "https://www.instagram.com/subhashreekhandai", img: "/Influencers/86.png", imgType: "photo", followers: "25.3k", location: "Kolkata" },
  { name: "Subhasmita Bal", handle: "onlythessb", link: "https://www.instagram.com/onlythessb", img: "/Influencers/87.png", imgType: "photo", followers: "18k", location: "Kolkata" },
  { name: "Sukanya Dutta", handle: "wowsukannya", link: "https://www.instagram.com/wowsukannya", img: "/Influencers/88.png", imgType: "avatar", followers: "66.7k" },
  { name: "Sulagna Dey", handle: "sulagnaaa.dey", link: "https://www.instagram.com/sulagnaaa.dey", img: "/Influencers/89.png", imgType: "photo", followers: "76.6k" },
  { name: "Sunitee Siddiqui", handle: "_hotmess_mama", link: "https://www.instagram.com/_hotmess_mama", img: "/Influencers/90.png", imgType: "photo", followers: "127k" },
  { name: "Susmita Das", handle: "dsusmita", link: "https://www.instagram.com/dsusmita", img: "/Influencers/91.png", imgType: "photo", followers: "118k", location: "Kolkata" },
  { name: "Susmitha Deb", handle: "officialsusmitadeb__", link: "https://www.instagram.com/officialsusmitadeb__", img: "/Influencers/92.png", imgType: "photo", followers: "235k" },
  { name: "Suvo Jit", handle: "suvlogging", link: "https://www.instagram.com/suvlogging", img: "/Influencers/93.png", imgType: "photo", followers: "4749", location: "Kolkata" },
  { name: "Sweta Patra", handle: "_vibing.high_", link: "https://www.instagram.com/_vibing.high_", img: "/Influencers/94.png", imgType: "photo", followers: "33.4k", location: "Kolkata" },
  { name: "Tanurima Hazra", handle: "tanurimahazra", link: "https://www.instagram.com/tanurimahazra", img: "/Influencers/95.png", imgType: "photo", followers: "107k" },
  { name: "Tithi Basu", handle: "c_h_i_r_p_s", link: "https://www.instagram.com/c_h_i_r_p_s", img: "/Influencers/96.png", imgType: "photo", followers: "164k" },
  { name: "Ira Chauhan", handle: "ira_chauhan12", link: "https://www.instagram.com/ira_chauhan12", img: "/Influencers/97.png", imgType: "photo", followers: "43.9K", location: "Chandigarh, India" },
  { name: "Tripti Guha", handle: "triptiggupta", link: "https://www.instagram.com/triptiggupta", img: "/Influencers/98.png", imgType: "photo", followers: "20.6k" },
  { name: "Trisha Ganguly", handle: "trisha_gunja_ganguly", link: "https://www.instagram.com/trisha_gunja_ganguly", img: "/Influencers/99.png", imgType: "photo", followers: "28 .8k" },
];
